blank_issues_enabled: true
contact_links:
  - name: Fråga eller idé / Question or idea
    url: https://discord.gg/kMVJ55wwy7
    about: För allt som inte är ett event eller ett turneringsresultat, prata med oss på Discord.
