start_date = "2026-08-07T19:00:00"
end_date = "2026-08-07T22:00:00"
price = 25
price_currency = "SEK"
cover = "/images/Marvel_Tokon_Release_Turnering_Nytt_datum.png"
checkin_time = "18:30"
challonge_url = "https://ceca1a6a1a76169ba1e5b00c.challonge.com/sv/d2v4xqw4"
discord_url = "https://discord.com/events/581034602865360898/1505650273073234000"

[location]
name = "Kappa Bar"
street = "Rosenlundsgatan 8"
postal_code = "411 20"
city = "Göteborg"
country = "SE"
